default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: v360ToDoListDev
  username: postgres
  password: juser123
  pool: 5
  host: localhost
  port: 5432


test:
  <<: *default
  database: v360ToDoListTst
  username: postgres
  password: juser123
  pool: 5
  host: localhost
  port: 5432

#
production:
  primary: &primary_production
    <<: *default
    database: v360_to_do_list_production
    username: <%= ENV["V360_TO_DO_LIST_DATABASE_USERNAME"] %>
    password: <%= ENV["V360_TO_DO_LIST_DATABASE_PASSWORD"] %>
    host: <%= ENV["V360_TO_DO_LIST_DATABASE_HOST"] %>
    port: <%= ENV["V360_TO_DO_LIST_DATABASE_PORT"] %>
  cache:
    <<: *primary_production
    database: v360_to_do_list_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: v360_to_do_list_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: v360_to_do_list_production_cable
    migrations_paths: db/cable_migrate
